import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    // Sidebar
    appName: 'LibraryOS',
    appSubtitle: 'Attendance & Fee Manager',
    overview: 'OVERVIEW',
    dailyWork: 'DAILY WORK',
    management: 'MANAGEMENT',
    dashboard: 'Dashboard',
    markAttendance: 'Mark Attendance',
    overdueFees: 'Overdue Fees',
    members: 'Members',
    feePayments: 'Fee Payments',
    staff: 'Staff',
    signOut: 'Sign Out',
    admin: 'ADMIN',

    // Dashboard
    dashboardTitle: 'Dashboard',
    totalMembers: 'Total Members',
    activeMembers: 'Active members',
    presentToday: 'Present Today',
    of: 'of',
    feesPaid: 'Fees Paid',
    overdue: 'Overdue',
    haventPaid: "Haven't paid this month",
    quickActions: 'Quick Actions',
    markTodayAttendance: "✅ Mark Today's Attendance",
    viewOverdueFees: '⚠️ View Overdue Fees',
    addNewMember: '👤 Add New Member',
    recentCheckIns: 'Recent Check-ins Today',
    noAttendanceYet: 'No attendance marked yet today.',
    loadingDashboard: 'Loading dashboard...',

    // Members
    membersTitle: 'Members',
    activeMembersCount: 'active members',
    addMember: '+ Add Member',
    removeMember: '− Remove Member',
    active: 'Active',
    inactive: 'Inactive',
    all: 'All',
    searchMembers: 'Search by name, ID, or phone...',
    memberId: 'Member ID',
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    monthlyFee: 'Monthly Fee',
    dueDay: 'Due Day',
    status: 'Status',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    noMembersFound: 'No members found.',
    addNewMemberTitle: 'Add New Member',
    editMemberTitle: 'Edit Member',
    memberIdLabel: 'Member ID *',
    fullName: 'Full Name *',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    address: 'Address',
    monthlyFeeLabel: 'Monthly Fee (₹)',
    dueDayLabel: 'Due Day of Month',
    statusLabel: 'Status',
    cancel: 'Cancel',
    saveMember: 'Save Member',
    nameRequired: 'Name and Member ID are required.',
    memberUpdated: 'Member updated.',
    memberAdded: 'Member added.',
    deleteMemberTitle: 'Delete Member',
    deleteMemberConfirm: 'Are you sure you want to delete',
    deleteMemberWarning: '? This will also delete all their attendance and fee records. This cannot be undone.',
    back: '← Back',
    deleteBtn: 'Delete',
    removeMemberTitle: 'Remove Member',
    selectMember: 'Select a member to remove:',
    searchMembersPlaceholder: 'Search members...',

    // Attendance
    attendanceTitle: 'Mark Attendance',
    attendanceSubtitle: 'Click a member card to mark present / absent',
    present: 'Present',
    absent: 'Absent',
    showing: 'Showing',
    markAllPresent: 'Mark All Present',
    searchByNameOrId: 'Search by name or member ID...',
    noMembersFoundSearch: 'No members found for',
    markAllConfirm: 'Mark ALL',
    visibleMembersPresent: 'visible members as present?',
    markedPresent: 'members as present.',

    // Fees
    feePaymentsTitle: 'Fee Payments',
    recordPayment: '+ Record Payment',
    searchFees: 'Search by member name or ID...',
    member: 'Member',
    month: 'Month',
    year: 'Year',
    amount: 'Amount',
    paidOn: 'Paid On',
    collectedBy: 'Collected By',
    noPayments: 'No payments found.',
    recordFeePayment: 'Record Fee Payment',
    selectMemberLabel: 'Member *',
    selectMemberOption: 'Select member...',
    monthLabel: 'Month *',
    yearLabel: 'Year *',
    amountLabel: 'Amount (₹) *',
    paidOnLabel: 'Paid On',
    notes: 'Notes (optional)',
    notesPlaceholder: 'e.g. Paid in cash',
    savePayment: 'Save Payment',
    selectMemberAmount: 'Select a member and enter amount.',
    paymentRecorded: 'Payment recorded.',
    alreadyPaid: 'already paid for',

    // Overdue
    overdueTitle: 'Overdue Fees',
    overdueSubtitle: 'Members who have not paid for the selected month',
    searchOverdue: 'Search by name, ID, or phone...',
    totalUnpaid: 'Total Unpaid',
    dueDate: 'Due Date',
    overdueBadge: 'Overdue',
    dueSoon: 'Due Soon',
    collectFee: 'Collect Fee',
    copyAlertList: '📋 Copy Alert List',
    noOverdue: 'All members have paid for this month! 🎉',
    membersUnpaid: 'members have not paid',
    copySuccess: 'Alert list copied to clipboard!',

    // Staff
    staffTitle: 'Staff',
    addStaff: '+ Add Staff',
    staffMember: 'Staff Member',
    role: 'Role',
    joined: 'Joined',
    addStaffTitle: 'Add Staff Member',
    fullNameLabel: 'Full Name',
    passwordLabel: 'Password',
    roleLabel: 'Role',
    allFieldsRequired: 'All fields are required.',
    passwordLength: 'Password must be at least 6 characters.',
    addStaffBtn: 'Add Staff',

    // Login
    signIn: 'Sign In',
    signInSubtitle: 'Sign in to manage attendance and fees',
    emailLabel2: 'EMAIL',
    passwordLabel2: 'PASSWORD',
    signingIn: 'Signing in...',
    noStaffProfile: '⚠️ Your account is not linked to a staff profile. Contact admin.',
    invalidCredentials: 'Invalid email or password.',
  },

  hi: {
    // Sidebar
    appName: 'लाइब्रेरी OS',
    appSubtitle: 'उपस्थिति और शुल्क प्रबंधक',
    overview: 'सारांश',
    dailyWork: 'दैनिक कार्य',
    management: 'प्रबंधन',
    dashboard: 'डैशबोर्ड',
    markAttendance: 'उपस्थिति दर्ज करें',
    overdueFees: 'बकाया शुल्क',
    members: 'सदस्य',
    feePayments: 'शुल्क भुगतान',
    staff: 'स्टाफ',
    signOut: 'साइन आउट',
    admin: 'व्यवस्थापक',

    // Dashboard
    dashboardTitle: 'डैशबोर्ड',
    totalMembers: 'कुल सदस्य',
    activeMembers: 'सक्रिय सदस्य',
    presentToday: 'आज उपस्थित',
    of: 'में से',
    feesPaid: 'शुल्क भुगतान',
    overdue: 'बकाया',
    haventPaid: 'इस महीने भुगतान नहीं किया',
    quickActions: 'त्वरित कार्य',
    markTodayAttendance: '✅ आज की उपस्थिति दर्ज करें',
    viewOverdueFees: '⚠️ बकाया शुल्क देखें',
    addNewMember: '👤 नया सदस्य जोड़ें',
    recentCheckIns: 'आज की हालिया उपस्थिति',
    noAttendanceYet: 'आज अभी तक कोई उपस्थिति दर्ज नहीं हुई।',
    loadingDashboard: 'डैशबोर्ड लोड हो रहा है...',

    // Members
    membersTitle: 'सदस्य',
    activeMembersCount: 'सक्रिय सदस्य',
    addMember: '+ सदस्य जोड़ें',
    removeMember: '− सदस्य हटाएं',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    all: 'सभी',
    searchMembers: 'नाम, ID या फ़ोन से खोजें...',
    memberId: 'सदस्य ID',
    name: 'नाम',
    phone: 'फ़ोन',
    email: 'ईमेल',
    monthlyFee: 'मासिक शुल्क',
    dueDay: 'देय दिन',
    status: 'स्थिति',
    actions: 'कार्रवाई',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    noMembersFound: 'कोई सदस्य नहीं मिला।',
    addNewMemberTitle: 'नया सदस्य जोड़ें',
    editMemberTitle: 'सदस्य संपादित करें',
    memberIdLabel: 'सदस्य ID *',
    fullName: 'पूरा नाम *',
    phoneLabel: 'फ़ोन',
    emailLabel: 'ईमेल',
    address: 'पता',
    monthlyFeeLabel: 'मासिक शुल्क (₹)',
    dueDayLabel: 'महीने का देय दिन',
    statusLabel: 'स्थिति',
    cancel: 'रद्द करें',
    saveMember: 'सदस्य सहेजें',
    nameRequired: 'नाम और सदस्य ID आवश्यक हैं।',
    memberUpdated: 'सदस्य अपडेट हुआ।',
    memberAdded: 'सदस्य जोड़ा गया।',
    deleteMemberTitle: 'सदस्य हटाएं',
    deleteMemberConfirm: 'क्या आप वाकई हटाना चाहते हैं',
    deleteMemberWarning: '? इससे उनकी सभी उपस्थिति और शुल्क रिकॉर्ड भी हट जाएंगे। यह क्रिया पूर्ववत नहीं की जा सकती।',
    back: '← वापस',
    deleteBtn: 'हटाएं',
    removeMemberTitle: 'सदस्य हटाएं',
    selectMember: 'हटाने के लिए सदस्य चुनें:',
    searchMembersPlaceholder: 'सदस्य खोजें...',

    // Attendance
    attendanceTitle: 'उपस्थिति दर्ज करें',
    attendanceSubtitle: 'उपस्थित / अनुपस्थित दर्ज करने के लिए कार्ड पर क्लिक करें',
    present: 'उपस्थित',
    absent: 'अनुपस्थित',
    showing: 'दिख रहे हैं',
    markAllPresent: 'सभी उपस्थित करें',
    searchByNameOrId: 'नाम या सदस्य ID से खोजें...',
    noMembersFoundSearch: 'कोई सदस्य नहीं मिला',
    markAllConfirm: 'क्या सभी',
    visibleMembersPresent: 'दिखते सदस्यों को उपस्थित करें?',
    markedPresent: 'सदस्य उपस्थित दर्ज किए।',

    // Fees
    feePaymentsTitle: 'शुल्क भुगतान',
    recordPayment: '+ भुगतान दर्ज करें',
    searchFees: 'सदस्य नाम या ID से खोजें...',
    member: 'सदस्य',
    month: 'महीना',
    year: 'वर्ष',
    amount: 'राशि',
    paidOn: 'भुगतान तिथि',
    collectedBy: 'संग्रहकर्ता',
    noPayments: 'कोई भुगतान नहीं मिला।',
    recordFeePayment: 'शुल्क भुगतान दर्ज करें',
    selectMemberLabel: 'सदस्य *',
    selectMemberOption: 'सदस्य चुनें...',
    monthLabel: 'महीना *',
    yearLabel: 'वर्ष *',
    amountLabel: 'राशि (₹) *',
    paidOnLabel: 'भुगतान तिथि',
    notes: 'नोट्स (वैकल्पिक)',
    notesPlaceholder: 'जैसे: नकद भुगतान',
    savePayment: 'भुगतान सहेजें',
    selectMemberAmount: 'सदस्य चुनें और राशि दर्ज करें।',
    paymentRecorded: 'भुगतान दर्ज हुआ।',
    alreadyPaid: 'पहले से भुगतान कर चुके हैं',

    // Overdue
    overdueTitle: 'बकाया शुल्क',
    overdueSubtitle: 'जिन सदस्यों ने चुने हुए महीने का भुगतान नहीं किया',
    searchOverdue: 'नाम, ID या फ़ोन से खोजें...',
    totalUnpaid: 'कुल बकाया',
    dueDate: 'देय तिथि',
    overdueBadge: 'बकाया',
    dueSoon: 'जल्द देय',
    collectFee: 'शुल्क लें',
    copyAlertList: '📋 सूची कॉपी करें',
    noOverdue: 'इस महीने सभी सदस्यों ने भुगतान कर दिया है! 🎉',
    membersUnpaid: 'सदस्यों ने भुगतान नहीं किया',
    copySuccess: 'अलर्ट सूची क्लिपबोर्ड पर कॉपी हुई!',

    // Staff
    staffTitle: 'स्टाफ',
    addStaff: '+ स्टाफ जोड़ें',
    staffMember: 'स्टाफ सदस्य',
    role: 'भूमिका',
    joined: 'जुड़े',
    addStaffTitle: 'स्टाफ सदस्य जोड़ें',
    fullNameLabel: 'पूरा नाम',
    passwordLabel: 'पासवर्ड',
    roleLabel: 'भूमिका',
    allFieldsRequired: 'सभी फ़ील्ड आवश्यक हैं।',
    passwordLength: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए।',
    addStaffBtn: 'स्टाफ जोड़ें',

    // Login
    signIn: 'साइन इन',
    signInSubtitle: 'उपस्थिति और शुल्क प्रबंधन के लिए साइन इन करें',
    emailLabel2: 'ईमेल',
    passwordLabel2: 'पासवर्ड',
    signingIn: 'साइन इन हो रहा है...',
    noStaffProfile: '⚠️ आपका खाता किसी स्टाफ प्रोफ़ाइल से जुड़ा नहीं है। व्यवस्थापक से संपर्क करें।',
    invalidCredentials: 'ईमेल या पासवर्ड गलत है।',
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  const toggleLang = () => setLang(l => l === 'en' ? 'hi' : 'en')
  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
